### PR TITLE
git account addition to the readers folder

### PR DESCRIPTION
**Pull request by mariorollojr**
Asking to be added to the readers folder

### CODE REVIEW

**Comment by jdblischak** [comment]
Hi, @mariorollojr! Thanks for reading through our tutorial and sending us a Pull Request (PR). Currently your PR does not include the file `readers/mariorollojr.txt`. Did you run `git add readers/mariorollojr.txt` prior to running `git commit`? Please let us know how we can help.

**Comment by mariorollojr** [comment]
Hi John. I followed your instructions on the paper and received this message from the prompt: remote: Permission to jdblischak/git-for-science.git denied to mariorollojr.
fatal: unable to access 'https://github.com/jdblischak/git-for-science/': The requested URL returned error: 403. So I tried to do this operation manually, directly from GitHub interface.

**Comment by jdblischak** [comment]
I see. The error is because you were trying to push your changes to my repository, which you do not have permission to edit. Instead you need to clone your fork of this repository and then push your changes to your fork. Thus the `git clone` command you should use is this:

```
$ git clone https://github.com/mariorollojr/git-for-science.git
```

Do you want to try cloning your fork and re-follow the directions in teh section [Contribute to Other Projects](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004668#sec011)? If yes, you can create a new PR and we'll close this attempt.

**Comment by jdblischak** [comment]
@mariorollojr Just checking in. Please let me know if you have any questions.

**Comment by jdblischak** [comment]
> So I tried to do this operation manually, directly from GitHub interface.

@mariorollojr Sorry. I missed the part where you said you used the GitHub interface. Reviewing this PR again I see that you did add the necessary file, so I'm merging now. Sorry for the confusion!

**Pull request merged**
