### PR TITLE
Adding updated main figures

### PR DESCRIPTION
**Pull request by erdavenport**
I added updated figures 2 and 3 (NewFig2 and NewFig3) and added them to the layout file. We can take a look at these and I'll keep working on them. I haven't removed the old figures 2 and 3 yet and I also haven't written legends yet. Let me know if you have any ideas for the figures! I'm totally stumped as to how to improve them!

### CODE REVIEW

**Comment by jdblischak** [comment]
OK. Just to make sure I understand. Figure 2 is basically a new figure. It demonstrates a simple local workflow. This is good. Then the previous Figure 2, which demonstrates pushing local changes to a remote, has been updated and moved to Figure 3. I also like this.

But with these changes we also need to decide what to do with the previous Figure 3 and the current Figure 4. Since one of our goals is to make the figures simpler and easier to quickly comprehend, I suggest we move the previous Figure 3 to be Figure 4 and then remove the current Figure 4 (while beautiful, I think it is just too daunting for a novice).

**Comment by erdavenport** [comment]
Yes, exactly. Figure 1 stayed the same. I added a new figure (Figure 2) to bridge the gap between what we're presenting in Figure 1 and the complexity of what was Figure 2 (and is now Figure 3). It simplifies what we're showing in the figures and more gradually builds up to the concepts of working with remote and local repos. Good, I'm glad you like the changes. If there any other suggestions you can think of, let me know and I'm happy to keep editing them.

Yeah, so, the reviewers suggested moving things to the supplement. I think the idea of supplemental material for an educational article is a little odd, so I would say we should cut anything we don't want included in the main text. I like the plan of moving former Figure 3 to be Figure 4 and axing former Figure 4. That figure is crazy!

**Comment by jdblischak** [comment]
Great. How would you like me to proceed with this PR? I can merge it now or wait for additional commits.

**Comment by erdavenport** [comment]
If there's nothing you want changed on these figures right now, go ahead and merge!

**Pull request merged**
