### PR TITLE
New Member Of GitForScience

### PR DESCRIPTION
**Pull request by AbelSaul**

### CODE REVIEW

**Comment by AbelSaul** [comment]
Thanks

**Comment by jdblischak** [comment]
@AbelSaul Thanks for following the tutorial and sending us a Pull Request!

I noticed that your GitHub username uses capital letters, but the file you committed is all lowercase. Would you be interested in fixing this yourself? I've provided the instructions below. If you'd prefer that I merge and then fix it, I'm also happy to do that. Just let me know.

```
cd git-for-science
git mv readers/abelsaul.txt readers/AbelSaul.txt
git commit -m "Capitalize GitHub username"
git push origin master
```

**Comment by jdblischak** [comment]
@AbelSaul Just checking in. Would you like to try and make the update and would you prefer to let me make the change?

**Comment by jdblischak** [comment]
@AbelSaul Thanks again for the PR! I went ahead and merged it and capitalized your username in commit b9cbc10

**Pull request merged**
